services:
  app:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src
    environment:
      - ENVIRONMENT=development  # 虽然是开发环境，但现在统一使用 PostgreSQL
      - DATABASE_URL=postgresql://my_agent:tangtao0123456@postgres:5432/agent_db?options=-cclient_encoding%3DUTF8
      - DASHSCOPE_API_KEY=sk-1f942692b9114f249b9da3b4b22c122e
      - HF_ENDPOINT=https://hf-mirror.com
    dns:
      - 223.5.5.5
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ./prompts:/app/prompts
      - ./data:/app/data
      - ./storage:/app/storage
      - ./frontend/dist:/app/frontend/dist
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg15
    container_name: qidian-postgres-dev
    environment:
      POSTGRES_DB: agent_db
      POSTGRES_USER: my_agent
      POSTGRES_PASSWORD: tangtao0123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_dev_data:
