chunk_size: 512
chunk_overlap: 20
similarity_top_k: 3
storage:
  chroma_dir: storage/chroma
  notion_collection: notion
  local_collection: local
data:
  local_dir: data/raw
csv_file: data/sales_data.csv
