package httpapi

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/starslittle/agent/go-backend/internal/auth"
	"github.com/starslittle/agent/go-backend/internal/config"
)

const (
	testSessionToken = "test-session-token"
	testCSRFToken    = "test-csrf-token"
)

func TestQueryStreamPreservesSSEBytesAndRequestID(t *testing.T) {
	var contract struct {
		Request  json.RawMessage `json:"request"`
		Response string          `json:"response"`
	}
	fixture, err := os.ReadFile(filepath.Join("testdata", "query_stream_contract.json"))
	if err != nil {
		t.Fatalf("read contract fixture: %v", err)
	}
	if err := json.Unmarshal(fixture, &contract); err != nil {
		t.Fatalf("decode contract fixture: %v", err)
	}
	expected := contract.Response

	receivedRequestID := make(chan string, 1)
	receivedBody := make(chan []byte, 1)
	receivedHeaders := make(chan http.Header, 1)
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		receivedRequestID <- r.Header.Get(requestIDHeader)
		receivedHeaders <- r.Header.Clone()
		body, _ := io.ReadAll(r.Body)
		receivedBody <- body
		if r.URL.Path != "/query_stream" {
			t.Errorf("upstream path = %q", r.URL.Path)
		}
		w.Header().Set("Content-Type", "text/event-stream; charset=utf-8")
		w.Header().Set("Set-Cookie", "python_cookie=must-not-reach-browser")
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.WriteHeader(http.StatusOK)
		_, _ = io.WriteString(w, expected[:len(expected)/2])
		w.(http.Flusher).Flush()
		_, _ = io.WriteString(w, expected[len(expected)/2:])
		w.(http.Flusher).Flush()
	}))
	defer upstream.Close()

	gateway := newTestGateway(t, upstream.URL)
	request := httptest.NewRequest(
		http.MethodPost,
		"/query_stream",
		bytes.NewReader(contract.Request),
	)
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set(requestIDHeader, "request-from-client")
	request.Header.Set("Authorization", "Bearer browser-token")
	request.Header.Set("X-Qidian-User-ID", "spoofed-user")
	request.Header.Set("X-Qidian-Signature", "spoofed-signature")
	request.AddCookie(&http.Cookie{Name: "browser_secret", Value: "must-not-reach-python"})
	authorizeTestRequest(request)
	response := httptest.NewRecorder()

	gateway.ServeHTTP(response, request)

	if response.Code != http.StatusOK {
		t.Fatalf("status = %d, body = %s", response.Code, response.Body.String())
	}
	if response.Body.String() != expected {
		t.Fatalf("SSE body changed:\n%q\nwant:\n%q", response.Body.String(), expected)
	}
	if response.Header().Get(requestIDHeader) != "request-from-client" {
		t.Fatalf("response request ID = %q", response.Header().Get(requestIDHeader))
	}
	if requestID := <-receivedRequestID; requestID != "request-from-client" {
		t.Fatalf("upstream request ID = %q", requestID)
	}
	headers := <-receivedHeaders
	if headers.Get("Cookie") != "" || headers.Get("Authorization") != "" {
		t.Fatal("browser credentials were forwarded to Python")
	}
	if headers.Get("X-Qidian-User-ID") != "00000000-0000-4000-8000-000000000001" {
		t.Fatalf("upstream user ID = %q", headers.Get("X-Qidian-User-ID"))
	}
	if headers.Get("X-Qidian-Signature") == "" ||
		headers.Get("X-Qidian-Signature") == "spoofed-signature" ||
		headers.Get("X-Qidian-Timestamp") == "" {
		t.Fatal("internal request signature was not generated by Go")
	}
	if response.Header().Get("Set-Cookie") != "" ||
		response.Header().Get("Access-Control-Allow-Origin") != "" {
		t.Fatal("internal Python response headers reached the browser")
	}
	var upstreamPayload map[string]any
	if err := json.Unmarshal(<-receivedBody, &upstreamPayload); err != nil {
		t.Fatalf("upstream request is not JSON: %v", err)
	}
	if upstreamPayload["agent_name"] != "default_llm_agent" {
		t.Fatalf("agent_name was changed: %#v", upstreamPayload["agent_name"])
	}
}

func TestQueryStreamValidatesRequest(t *testing.T) {
	gateway := newTestGateway(t, "http://127.0.0.1:1")
	request := httptest.NewRequest(
		http.MethodPost,
		"/query_stream",
		strings.NewReader(`{"query":"   "}`),
	)
	request.Header.Set("Content-Type", "application/json")
	authorizeTestRequest(request)
	response := httptest.NewRecorder()

	gateway.ServeHTTP(response, request)

	if response.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want %d", response.Code, http.StatusBadRequest)
	}
}

func TestHealthAndReadiness(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/internal/ready" {
			http.NotFound(w, r)
			return
		}
		writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
	}))
	defer upstream.Close()
	gateway := newTestGateway(t, upstream.URL)

	for _, path := range []string{"/healthz", "/readyz"} {
		request := httptest.NewRequest(http.MethodGet, path, nil)
		response := httptest.NewRecorder()
		gateway.ServeHTTP(response, request)
		if response.Code != http.StatusOK {
			t.Fatalf("%s status = %d", path, response.Code)
		}
		var payload map[string]any
		if err := json.Unmarshal(response.Body.Bytes(), &payload); err != nil {
			t.Fatalf("%s invalid JSON: %v", path, err)
		}
	}
}

func TestStaticFilesAndSPAFallback(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})
	}))
	defer upstream.Close()

	staticDir := t.TempDir()
	if err := os.WriteFile(
		filepath.Join(staticDir, "index.html"),
		[]byte("<main>qidian app</main>"),
		0o600,
	); err != nil {
		t.Fatalf("write index fixture: %v", err)
	}
	if err := os.WriteFile(
		filepath.Join(staticDir, "asset.txt"),
		[]byte("static asset"),
		0o600,
	); err != nil {
		t.Fatalf("write asset fixture: %v", err)
	}

	cfg := config.Config{
		HTTPAddr:              ":0",
		PythonBaseURL:         upstream.URL,
		StaticDir:             staticDir,
		MaxRequestBytes:       1 << 20,
		UpstreamHeaderTimeout: 2 * time.Second,
		ShutdownTimeout:       time.Second,
	}
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	server, err := New(cfg, logger, newTestAuthService())
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	for path, expected := range map[string]string{
		"/asset.txt":  "static asset",
		"/chat/12345": "<main>qidian app</main>",
	} {
		request := httptest.NewRequest(http.MethodGet, path, nil)
		response := httptest.NewRecorder()
		server.Handler().ServeHTTP(response, request)
		if response.Code != http.StatusOK {
			t.Fatalf("%s status = %d", path, response.Code)
		}
		if strings.TrimSpace(response.Body.String()) != expected {
			t.Fatalf("%s body = %q", path, response.Body.String())
		}
	}
}

func TestClientCancellationPropagatesToPython(t *testing.T) {
	started := make(chan struct{})
	cancelled := make(chan struct{})
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/event-stream")
		w.WriteHeader(http.StatusOK)
		w.(http.Flusher).Flush()
		close(started)
		<-r.Context().Done()
		close(cancelled)
	}))
	defer upstream.Close()

	gateway := httptest.NewServer(newTestGateway(t, upstream.URL))
	defer gateway.Close()
	ctx, cancel := context.WithCancel(context.Background())
	request, err := http.NewRequestWithContext(
		ctx,
		http.MethodPost,
		gateway.URL+"/query_stream",
		strings.NewReader(`{"query":"等待"}`),
	)
	if err != nil {
		t.Fatalf("NewRequestWithContext() error = %v", err)
	}
	request.Header.Set("Content-Type", "application/json")
	authorizeTestRequest(request)
	response, err := http.DefaultClient.Do(request)
	if err != nil {
		t.Fatalf("gateway request error = %v", err)
	}

	select {
	case <-started:
	case <-time.After(2 * time.Second):
		t.Fatal("upstream request did not start")
	}
	cancel()
	_ = response.Body.Close()

	select {
	case <-cancelled:
	case <-time.After(2 * time.Second):
		t.Fatal("upstream context was not cancelled")
	}
}

func newTestGateway(t *testing.T, pythonBaseURL string) http.Handler {
	t.Helper()
	cfg := config.Config{
		HTTPAddr:              ":0",
		PythonBaseURL:         pythonBaseURL,
		MaxRequestBytes:       1 << 20,
		UpstreamHeaderTimeout: 2 * time.Second,
		ShutdownTimeout:       time.Second,
		InternalAgentSecret:   "test-secret-that-is-at-least-32-characters",
	}
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	server, err := New(cfg, logger, newTestAuthService())
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}
	return server.Handler()
}

func TestAuthLifecycle(t *testing.T) {
	upstream := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/event-stream")
		_, _ = io.WriteString(w, "event: message\r\ndata: {\"type\":\"done\"}\r\n\r\n")
	}))
	defer upstream.Close()

	store := newMemoryAuthStore()
	service := auth.NewService(store, time.Hour)
	cfg := config.Config{
		AppEnv:                "test",
		HTTPAddr:              ":0",
		PythonBaseURL:         upstream.URL,
		MaxRequestBytes:       1 << 20,
		UpstreamHeaderTimeout: 2 * time.Second,
		ShutdownTimeout:       time.Second,
		SessionTTL:            time.Hour,
		InternalAgentSecret:   "test-secret-that-is-at-least-32-characters",
	}
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	server, err := New(cfg, logger, service)
	if err != nil {
		t.Fatalf("New() error = %v", err)
	}

	register := httptest.NewRequest(
		http.MethodPost,
		"/api/v1/auth/register",
		strings.NewReader(`{"email":"person@example.com","password":"a secure password 123","display_name":"测试用户"}`),
	)
	register.Header.Set("Content-Type", "application/json")
	registerResponse := httptest.NewRecorder()
	server.Handler().ServeHTTP(registerResponse, register)
	if registerResponse.Code != http.StatusCreated {
		t.Fatalf("register status = %d, body = %s", registerResponse.Code, registerResponse.Body.String())
	}
	cookies := registerResponse.Result().Cookies()
	if len(cookies) != 1 || !cookies[0].HttpOnly ||
		cookies[0].SameSite != http.SameSiteLaxMode {
		t.Fatalf("unexpected session cookie: %#v", cookies)
	}
	var registered struct {
		CSRFToken string `json:"csrf_token"`
	}
	if err := json.Unmarshal(registerResponse.Body.Bytes(), &registered); err != nil {
		t.Fatalf("decode register response: %v", err)
	}
	if registered.CSRFToken == "" {
		t.Fatal("register response did not contain a CSRF token")
	}

	stream := httptest.NewRequest(
		http.MethodPost,
		"/query_stream",
		strings.NewReader(`{"query":"hello"}`),
	)
	stream.Header.Set("Content-Type", "application/json")
	stream.Header.Set("X-CSRF-Token", registered.CSRFToken)
	stream.AddCookie(cookies[0])
	streamResponse := httptest.NewRecorder()
	server.Handler().ServeHTTP(streamResponse, stream)
	if streamResponse.Code != http.StatusOK {
		t.Fatalf(
			"authenticated stream status = %d, body = %s",
			streamResponse.Code,
			streamResponse.Body.String(),
		)
	}

	logout := httptest.NewRequest(http.MethodPost, "/api/v1/auth/logout", nil)
	logout.Header.Set("X-CSRF-Token", registered.CSRFToken)
	logout.AddCookie(cookies[0])
	logoutResponse := httptest.NewRecorder()
	server.Handler().ServeHTTP(logoutResponse, logout)
	if logoutResponse.Code != http.StatusNoContent {
		t.Fatalf("logout status = %d, body = %s", logoutResponse.Code, logoutResponse.Body.String())
	}
}

func authorizeTestRequest(request *http.Request) {
	request.AddCookie(&http.Cookie{
		Name:  "qidian_session",
		Value: testSessionToken,
	})
	request.Header.Set("X-CSRF-Token", testCSRFToken)
}

func newTestAuthService() *auth.Service {
	store := newMemoryAuthStore()
	tokenHash := sha256.Sum256([]byte(testSessionToken))
	user := auth.User{
		ID:          "00000000-0000-4000-8000-000000000001",
		Email:       "test@example.com",
		DisplayName: "Test User",
		Status:      "active",
		CreatedAt:   time.Now().UTC(),
	}
	store.users[user.ID] = auth.Credential{User: user}
	store.emails[user.Email] = user.ID
	store.sessions[string(tokenHash[:])] = auth.Session{
		ID:         "00000000-0000-4000-8000-000000000002",
		User:       user,
		CSRFToken:  testCSRFToken,
		CreatedAt:  time.Now().UTC(),
		LastSeenAt: time.Now().UTC(),
		ExpiresAt:  time.Now().Add(time.Hour).UTC(),
	}
	return auth.NewService(store, time.Hour)
}

type memoryAuthStore struct {
	mu       sync.Mutex
	users    map[string]auth.Credential
	emails   map[string]string
	sessions map[string]auth.Session
}

func newMemoryAuthStore() *memoryAuthStore {
	return &memoryAuthStore{
		users:    make(map[string]auth.Credential),
		emails:   make(map[string]string),
		sessions: make(map[string]auth.Session),
	}
}

func (s *memoryAuthStore) Ping(context.Context) error { return nil }

func (s *memoryAuthStore) CreateUser(
	_ context.Context,
	params auth.CreateUserParams,
) (auth.User, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, exists := s.emails[params.Email]; exists {
		return auth.User{}, auth.ErrEmailExists
	}
	user := auth.User{
		ID:          params.ID,
		Email:       params.Email,
		DisplayName: params.DisplayName,
		Status:      "active",
		CreatedAt:   time.Now().UTC(),
	}
	s.users[user.ID] = auth.Credential{
		User:         user,
		PasswordHash: params.PasswordHash,
	}
	s.emails[user.Email] = user.ID
	return user, nil
}

func (s *memoryAuthStore) FindCredentialByEmail(
	_ context.Context,
	email string,
) (auth.Credential, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	userID, ok := s.emails[email]
	if !ok {
		return auth.Credential{}, auth.ErrInvalidCredentials
	}
	return s.users[userID], nil
}

func (s *memoryAuthStore) CreateSession(
	_ context.Context,
	params auth.CreateSessionParams,
) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	credential, ok := s.users[params.UserID]
	if !ok {
		return errors.New("user not found")
	}
	s.sessions[string(params.TokenHash)] = auth.Session{
		ID:         params.ID,
		User:       credential.User,
		CSRFToken:  params.CSRFToken,
		CreatedAt:  time.Now().UTC(),
		LastSeenAt: time.Now().UTC(),
		ExpiresAt:  params.ExpiresAt,
	}
	return nil
}

func (s *memoryAuthStore) FindSession(
	_ context.Context,
	tokenHash []byte,
	now time.Time,
) (auth.Session, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	session, ok := s.sessions[string(tokenHash)]
	if !ok || !now.Before(session.ExpiresAt) {
		return auth.Session{}, auth.ErrInvalidSession
	}
	return session, nil
}

func (s *memoryAuthStore) TouchSession(
	_ context.Context,
	id string,
	now time.Time,
) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	for key, session := range s.sessions {
		if session.ID == id {
			session.LastSeenAt = now
			s.sessions[key] = session
		}
	}
	return nil
}

func (s *memoryAuthStore) DeleteSession(
	_ context.Context,
	tokenHash []byte,
) error {
	s.mu.Lock()
	delete(s.sessions, string(tokenHash))
	s.mu.Unlock()
	return nil
}

func (s *memoryAuthStore) RecordLoginAudit(
	context.Context,
	auth.LoginAudit,
) error {
	return nil
}
